### ISSUE TITLE
Homescreen

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#17]
<h1>Story #1 Registration </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] Go to register button (start)
- [x] Go to login button (start)
- [x] Register button (registration)
- [x] Back to start button (registration)

 <h2>Estimate: 1h</h2>

**Comment by maxi1123** [comment]
b6944b65ddda0ca159a72a2938636886da31d124
