### ISSUE TITLE
Screen for menu

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#19]
<h1>Story #2 Login </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] "Play", "Leaderboards", "Tutorial" button 
- [x] "My Profile", "Logout", "About us" sidebar buttons

 <h2>Estimate: 2h</h2>

**Comment by maxi1123** [comment]
d30520ab827e6a51ac7e2c607fcc4f5fd993dbb8
