### ISSUE TITLE
Screen for profile

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#20]
<h1>Story #3 Profile </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] Display Username, ELO Score, Games Played and Games Won
- [x] Edit profile button
- [x] Back to menu button

 <h2>Estimate: 4h</h2>

**Comment by maxi1123** [comment]
4ef7994b73c08156028ba9164b5e906bbc20eaac
