### ISSUE TITLE
Screen for tutorial

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#21]
<h1>Story #4 Tutorial </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] Display text of rules
~~- [ ] Display interactions with the game with images~~
- [x] Back to menu button

 <h2>Estimate: 8h</h2>

**Comment by maxi1123** [comment]
95d74ede4f155dc7ff60b70b8beb75824e08db99
