### ISSUE TITLE
Screen for leaderboards

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#22]
<h1>Story #5 Leaderboards </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] Display top 5 players with their ELO
- [x] Player-Search field 
- [x] Click on name to direct to profile
- [x] Back to menu button

 <h2>Estimate: 6h</h2>

**Comment by maxi1123** [comment]
25f503db2946cecc5dd45f68e54914f8ac553dd3
