### ISSUE TITLE
Screen for lobby finder

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#24]
<h1>Story #7 Lobby Finder </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
~~- [ ] Lobby search field~~
- [x] Display the lobby infos (status, players, protection)
- [x] Refresh button

 <h2>Estimate: 4h</h2>

**Comment by maxi1123** [comment]
28f813f937bd9e0861bde947b33e5ad6fdc9602b
