### ISSUE TITLE
Screen for lobby

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#25]
<h1>Story #8 Lobby </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] Display all players in the lobby
- [x] Mark the creater with icon
- [x] Ready button
- [x] Start button

 <h2>Estimate: 7h</h2>

**Comment by maxi1123** [comment]
c152dc9e887fe4520437f8d1c4ff66c854ac69e9
