### ISSUE TITLE
Generate active picture location token

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#27]
<h1>Story #10 Active Picture </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] Button to generate location token for active picture
- [x] Redirect automatically to the picture recreation screen
- [x] Display the chosen active picture for the player that recreates it this round

 <h2>Estimate: 5h</h2>

**Comment by maxi1123** [comment]
25c1ed3b579888aef5b592715e05619fe301a11e
