### ISSUE TITLE
Screen for picture recreation 

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#28]
<h1>Story #11 Active Picture Recreation </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] Complete button
- [x] Display the recreated version of the picture
- [x] Redirect automatically to the guessing screen after every player pressed the complete button

 <h2>Estimate: 2h</h2>

**Comment by arjvillan** [comment]
d3052b6014f936f02a38d96c2577dd3745b3679d
