### ISSUE TITLE
Set #1 tiles for recreation

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#29]
<h1>Story #15 Material Sets </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] Frame to place tiles
- [x] Tiles to place into the frame
- [x] Drag and drop tiles from sidebar

 <h2>Estimate: 8h</h2>

**Comment by arjvillan** [comment]
4b7ebd7ef27da30a1e528668967f14f207a4d995
