### ISSUE TITLE
Set #2 building forms for recreation

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#30]
<h1>Story #15 Material Sets </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] Frame to place forms
- [x] Forms to place into the frame (triangles, circles, squares, moons etc.)
- [x] Drag and drop forms from sidebar into the frame

 <h2>Estimate: 8h</h2>

**Comment by arjvillan** [comment]
470b37e6249ea9c509313c48e493a41a674fa5cd
