### ISSUE TITLE
Set #3 stick and stones for recreation

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#31]
<h1>Story #15 Material Sets </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] Frame to place stick and stones in
- [x] Small variation of four different sticks (size, shape, branches)
- [x] Small variation of four different stones (size, shape)

 <h2>Estimate: 8h</h2>

**Comment by arjvillan** [comment]
9fa8c8e23d2c41102ff0029da6c118a7a734a8b4
