### ISSUE TITLE
Set #5 laces for recreation

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#33]
<h1>Story #15 Material Sets </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] Frame to draw the lace
- [x] Draw lace
- [x] Dont allow to continue drawing

 <h2>Estimate: 8h</h2>

**Comment by arjvillan** [comment]
d7ca39d55b53527827618ebfeef14bcc76f19150
