### ISSUE TITLE
Screen for guessing recreations

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#34]
<h1>Story #12 Recreation Guessing </h1>

 <h2>Sub-Tasks:</h2>

- [x] CSS
- [x] Display the original picture grid
- [x] Display the recreations in a second grid or list
- [x] Fields for guessing on each recreation
- [x] Submit guess button
- [x] When all players submited the client redirects to scoring at end of round/game
~~- [ ] Countdown that triggers a random guess on all empty fields after it hit zero~~

 <h2>Estimate: 10h</h2>

**Comment by maxi1123** [comment]
8dafcbb5780921dbb5b0d0eaca00e0e00598d467
