### ISSUE TITLE
Add points of round and each player to the score sheet

### ISSUE THREAD

**Issue by InfoYak** [sopra-fs21-group-26/client#36]
<h1>Story #16 Add Points to Score Sheet </h1>

 <h2>Sub-Tasks:</h2>

~~- [ ] Add points of each player to score sheet via REST `/lobbies/{lobbyId}/score/{playerId}`~~

 <h2>Estimate: 0.5h</h2>

**Comment by maxi1123** [comment]
Different logic. Issue closed.
